spring:
  datasource:
    password: wushudi1
    username: root
    url: jdbc:mysql://localhost:3306/bookweb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 8090
mybatis:
  type-aliases-package: com.first.pojo
  mapper-locations: classpath:Mybatis/*.xml
